const PHRASE_REPLACEMENTS: Array<[RegExp, string]> = [
  [/Always search tools first for current schemas\.?/gi, 'Toujours rechercher les outils en premier pour obtenir les schémas à jour.'],
  [/This skill should be used when the user asks to/gi, "Cette compétence doit être utilisée lorsque l'utilisateur demande de"],
  [/This skill should be used when users want to/gi, 'Cette compétence doit être utilisée lorsque les utilisateurs veulent'],
  [/This skill should be used when the user wants to/gi, "Cette compétence doit être utilisée lorsque l'utilisateur veut"],
  [/This skill should be used when the user asks about/gi, "Cette compétence doit être utilisée lorsque l'utilisateur demande des informations sur"],
  [/Use this skill when/gi, 'Utilisez cette compétence lorsque'],
  [/Use when/gi, 'À utiliser lorsque'],
  [/Use PROACTIVELY/gi, 'À utiliser de manière proactive'],
  [/You are an?/gi, 'Vous êtes un'],
  [/You are /gi, 'Vous êtes '],
  [/When Claude needs to/gi, 'Quand Claude doit'],
  [/When the user asks to/gi, "Quand l'utilisateur demande de"],
  [/When the user wants to/gi, "Quand l'utilisateur veut"],
  [/Key insight:/gi, 'Point clé :'],
  [/Best practices/gi, 'Bonnes pratiques'],
  [/Triggers:/gi, 'Déclencheurs :'],
  [/Use when:/gi, 'À utiliser quand :']
];

const WORD_REPLACEMENTS: Record<string, string> = {
  and: 'et',
  or: 'ou',
  for: 'pour',
  use: 'utiliser',
  when: 'quand',
  with: 'avec',
  to: 'pour',
  the: 'le',
  an: 'un',
  in: 'dans',
  a: 'un',
  need: 'besoin',
  needs: 'a besoin',
  address: 'traiter',
  issue: 'problème',
  comments: 'commentaires',
  comment: 'commentaire',
  where: 'où',
  even: 'même',
  top: 'meilleurs',
  this: 'cette',
  skill: 'compétence',
  using: 'en utilisant',
  management: 'gestion',
  tools: 'outils',
  build: 'créer',
  creating: 'création',
  implementing: 'implémentation',
  code: 'code',
  proactively: 'de manière proactive',
  via: 'via',
  design: 'conception',
  security: 'sécurité',
  api: 'api',
  building: 'création',
  automate: 'automatiser',
  data: 'données',
  patterns: 'modèles',
  pattern: 'modèle',
  create: 'créer',
  comprehensive: 'complet',
  testing: 'tests',
  performance: 'performance',
  analysis: 'analyse',
  current: 'actuels',
  always: 'toujours',
  optimization: 'optimisation',
  tasks: 'tâches',
  first: 'en premier',
  architecture: 'architecture',
  applications: 'applications',
  specializing: 'spécialisé',
  web: 'web',
  covers: 'couvre',
  modern: 'moderne',
  content: 'contenu',
  on: 'sur',
  systems: 'systèmes',
  development: 'développement',
  that: 'qui',
  from: 'de',
  including: 'y compris',
  agents: 'agents',
  of: 'de',
  you: 'vous',
  master: 'maîtriser',
  managing: 'gestion',
  java: 'java',
  are: 'êtes',
  strategies: 'stratégies',
  best: 'meilleures',
  manage: 'gérer',
  database: 'base de données',
  agent: 'agent',
  react: 'react',
  should: 'doit',
  be: 'être',
  asks: 'demande',
  python: 'python',
  operations: 'opérations',
  project: 'projet',
  used: 'utilisée',
  test: 'tester',
  rust: 'rust',
  review: 'revue',
  system: 'système',
  documentation: 'documentation',
  service: 'service',
  up: 'en place',
  key: 'clé',
  practices: 'pratiques',
  implement: 'implémenter',
  error: 'erreur',
  masters: 'maîtrise',
  workflows: 'workflows',
  workflow: 'workflow',
  debugging: 'débogage',
  any: 'tout',
  across: 'à travers',
  cloud: 'cloud',
  javascript: 'javascript',
  'real-time': 'temps réel',
  voice: 'voix',
  it: 'il',
  handling: 'gestion',
  authentication: 'authentification',
  services: 'services',
  application: 'application',
  working: 'travail',
  wants: 'veut',
  app: 'application',
  event: 'événement',
  tests: 'tests',
  advanced: 'avancé',
  ui: 'ui',
  infrastructure: 'infrastructure',
  document: 'document',
  typescript: 'typescript',
  custom: 'personnalisé',
  setting: 'configuration',
  production: 'production',
  'production-ready': 'prêt pour la production',
  async: 'asynchrone',
  complex: 'complexe',
  issues: 'problèmes',
  context: 'contexte',
  writing: 'écriture',
  projects: 'projets',
  vulnerabilities: 'vulnérabilités',
  automation: 'automatisation',
  provides: 'fournit',
  storage: 'stockage',
  generate: 'générer',
  handles: 'gère',
  llm: 'llm',
  file: 'fichier',
  features: 'fonctionnalités',
  integration: 'intégration',
  technical: 'technique',
  configuration: 'configuration',
  pages: 'pages',
  analytics: 'analytique',
  quality: 'qualité',
  net: '.net',
  text: 'texte',
  distributed: 'distribué',
  is: 'est',
  apis: 'apis',
  implementation: 'implémentation',
  components: 'composants',
  state: 'état',
  new: 'nouveau',
  streaming: 'streaming',
  monitor: 'surveiller',
  through: 'via',
  injection: 'injection',
  observability: 'observabilité',
  write: 'écrire',
  structured: 'structuré',
  container: 'conteneur',
  pipelines: 'pipelines',
  events: 'événements',
  tracking: 'suivi',
  optimizing: 'optimisation',
  creation: 'création',
  deployment: 'déploiement',
  apps: 'applications',
  models: 'modèles',
  monitoring: 'surveillance',
  microsoft: 'microsoft',
  into: 'dans',
  metrics: 'métriques',
  compliance: 'conformité',
  optimize: 'optimiser',
  component: 'composant',
  audio: 'audio',
  requests: 'requêtes',
  analyze: 'analyser',
  model: 'modèle',
  resource: 'ressource',
  task: 'tâche',
  files: 'fichiers',
  marketing: 'marketing',
  product: 'produit',
  framework: 'framework',
  image: 'image',
  work: 'travail',
  techniques: 'techniques',
  browser: 'navigateur',
  jobs: 'jobs',
  server: 'serveur',
  sql: 'sql',
  perform: 'effectuer',
  research: 'recherche',
  prompt: 'prompt',
  engineering: 'ingénierie',
  'ai-powered': 'alimenté par l’ia',
  batch: 'lot',
  dependency: 'dépendance',
  backend: 'backend',
  queries: 'requêtes',
  expert: 'expert',
  guide: 'guide',
  setup: 'configuration',
  principles: 'principes',
  scalable: 'évolutif',
  maintainable: 'maintenable',
  robust: 'robuste',
  efficient: 'efficace',
  reliable: 'fiable',
  reusable: 'réutilisable',
  templates: 'modèles',
  migration: 'migration',
  legacy: 'hérité',
  upgrade: 'mise à niveau',
  validation: 'validation',
  troubleshooting: 'dépannage',
  bug: 'bug',
  bugs: 'bugs',
  report: 'rapport',
  reports: 'rapports',
  dashboard: 'tableau de bord',
  dashboards: 'tableaux de bord',
  ci: 'ci',
  cd: 'cd',
  deploy: 'déployer',
  deploys: 'déploiements',
  secure: 'sécurisé',
  threat: 'menace',
  threats: 'menaces',
  audit: 'audit',
  audits: 'audits',
  package: 'package',
  packages: 'packages',
  library: 'bibliothèque',
  libraries: 'bibliothèques',
  endpoint: 'endpoint',
  endpoints: 'endpoints',
  command: 'commande',
  commands: 'commandes',
  support: 'support',
  supports: 'prend en charge',
  improve: 'améliorer',
  improves: 'améliore',
  improvement: 'amélioration',
  planning: 'planification',
  strategy: 'stratégie',
  search: 'recherche',
  foundry: 'foundry',
  skills: 'compétences',
  user: 'utilisateur',
  users: 'utilisateurs',
  local: 'local',
  remote: 'distant',
  cli: 'cli',
  open: 'ouvrir',
  source: 'source',
  experience: 'expérience',
  experiences: 'expériences',
  interactive: 'interactif',
  scene: 'scène',
  scenes: 'scènes',
  products: 'produits',
  configurator: 'configurateur',
  configurators: 'configurateurs',
  immersive: 'immersif',
  website: 'site web',
  websites: 'sites web',
  bringing: 'apportant',
  depth: 'profondeur',
  mandatory: 'obligatoires',
  gates: 'étapes',
  hypothesis: 'hypothèse',
  execution: 'exécution',
  readiness: 'préparation',
  accessibility: 'accessibilité',
  assistive: 'assistive',
  technology: 'technologie',
  compatibility: 'compatibilité',
  conduct: 'mener',
  identify: 'identifier',
  barriers: 'obstacles',
  provide: 'fournir',
  remediation: 'remédiation',
  guidance: 'conseils',
  attack: 'attaquer',
  exploit: 'exploiter',
  enumeration: 'énumération',
  relay: 'relais',
  windows: 'windows',
  domain: 'domaine',
  penetration: 'intrusion',
  list: 'liste',
  subscriptions: 'abonnements',
  enrollment: 'inscription',
  pull: 'pull',
  request: 'request',
  benchmarking: 'benchmark',
  benchmark: 'benchmark',
  behavioral: 'comportemental',
  capability: 'capacité',
  reliability: 'fiabilité',
  achieve: 'atteignent',
  less: 'moins',
  than: 'que',
  real: 'réel',
  world: 'monde',
  persistent: 'persistants',
  hosted: 'hébergés',
  interpreter: 'interpréteur',
  integrating: 'intégrant',
  conversation: 'conversation',
  threads: 'fils',
  responses: 'réponses',
  response: 'réponse',
  function: 'fonction',
  outputs: 'sorties',
  output: 'sortie',
  multiple: 'multiples',
  start: 'démarrer',
  stop: 'arrêter',
  assign: 'assigner',
  hybrid: 'hybride',
  memory: 'mémoire',
  searchable: 'recherchable',
  knowledge: 'connaissance',
  decisions: 'décisions',
  decision: 'décision',
  intelligent: 'intelligent',
  without: 'sans',
  interaction: 'interaction',
  starts: 'commence',
  short: 'court',
  long: 'long',
  cognitive: 'cognitif',
  organize: 'organisent',
  just: 'seulement',
  retrieval: 'récupération',
  million: 'million',
  stored: 'stockés',
  facts: 'faits',
  mean: 'signifient',
  nothing: 'rien',
  right: 'bonne',
  chunking: 'segmentation',
  embedding: 'embedding',
  embeddings: 'embeddings',
  determine: 'déterminent',
  remembers: 'se souvient',
  forgets: 'oublie',
  keyword: 'mot-clé',
  keywords: 'mots-clés',
  mention: 'mentionne',
  mentions: 'mentions',
  includes: 'inclut',
  include: 'inclure',
  based: 'basé',
  ready: 'prêt',
  complete: 'complet',
  overview: 'vue d’ensemble',
  stack: 'stack',
  frontend: 'front-end',
  mobile: 'mobile'
};

const KEEP_AS_IS = new Set([
  'api',
  'apis',
  'sdk',
  'llm',
  'rag',
  'react',
  'next.js',
  'nextjs',
  'typescript',
  'javascript',
  'python',
  'java',
  'rust',
  'golang',
  'node.js',
  'nodejs',
  'oauth',
  'jwt',
  'xss',
  'csrf',
  'mcp',
  'webgl',
  'three.js',
  'docker',
  'kubernetes',
  'k8s',
  'sql',
  'postgres',
  'postgresql',
  'mysql',
  'redis',
  'grpc',
  'graphql',
  'rest',
  'ga4',
  'utm',
  'ios',
  'android',
  'swiftui',
  'azure',
  'aws',
  'gcp',
  'github',
  'gitlab',
  'bitbucket',
  'playwright',
  'vite',
  'tailwind',
  'css',
  'html',
  'json',
  'yaml',
  'csv',
  'pdf',
  'sso',
  'saml',
  'pci',
  'gdpr',
  'hipaa',
  'soc2'
]);

const descriptionCache = new Map<string, string>();

function applyCase(source: string, target: string): string {
  if (source.toUpperCase() === source) {
    return target.toUpperCase();
  }

  if (source[0] === source[0].toUpperCase() && source.slice(1) === source.slice(1).toLowerCase()) {
    return target[0].toUpperCase() + target.slice(1);
  }

  return target;
}

function translateWordLevel(text: string): string {
  return text.replace(/\b[A-Za-z][A-Za-z0-9+.'-]*\b/g, (token) => {
    if (token.length === 1) {
      return token;
    }

    const normalized = token.toLowerCase();

    if (KEEP_AS_IS.has(normalized)) {
      return token;
    }

    const replacement = WORD_REPLACEMENTS[normalized];
    if (!replacement) {
      return token;
    }

    return applyCase(token, replacement);
  });
}

export function getLocalizedDescription(description: string, lang: 'en' | 'fr'): string {
  if (lang !== 'fr') {
    return description;
  }

  const cached = descriptionCache.get(description);
  if (cached) {
    return cached;
  }

  let translated = description;

  for (const [pattern, replacement] of PHRASE_REPLACEMENTS) {
    translated = translated.replace(pattern, replacement);
  }

  translated = translateWordLevel(translated)
    .replace(/\s{2,}/g, ' ')
    .replace(/\s+([,.;:!?])/g, '$1')
    .replace(/\(\s+/g, '(')
    .replace(/\s+\)/g, ')')
    .trim();

  descriptionCache.set(description, translated);
  return translated;
}

const RISK_FR: Record<string, string> = {
  safe: 'sûr',
  none: 'aucun',
  unknown: 'inconnu'
};

const SOURCE_FR: Record<string, string> = {
  unknown: 'inconnu'
};

export function getLocalizedRisk(risk: string, lang: 'en' | 'fr'): string {
  if (lang !== 'fr') {
    return risk;
  }
  return RISK_FR[risk.toLowerCase()] ?? risk;
}

export function getLocalizedSource(source: string, lang: 'en' | 'fr'): string {
  if (lang !== 'fr') {
    return source;
  }
  return SOURCE_FR[source.toLowerCase()] ?? source;
}
